# Generated by Django 3.2 on 2021-04-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_todoitem_finished"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todoitem",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="todoitem",
            name="finished",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="todolist",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
